import {create} from './StyleSheet.js';
import {ptd} from '../styles/SizeHelper.js';
export default create({
  bg:{
    android:{
        backgroundColor: '#f8f8f8',
    }
  },
  homeHeader:{
    position:'relative',
    marginBottom: ptd(-100),
  },
  bgDefault:{
    width:ptd(750),
    height:ptd(370)
  },
  infoBg:{
    width:ptd(750),
    height:ptd(370),
    backgroundColor:'rgba(27, 199, 135, .9)',
    color:'#fff',
    position:'absolute',
    top:0,
    paddingHorizontal:ptd(40),
    paddingVertical:ptd(46),
    paddingTop:ptd(66),
  },
  infoProfile:{
    height:ptd(80),
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    marginBottom:ptd(28),
    paddingRight:ptd(40),
  },
  titleBlock:{
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
  },
  title:{
    fontFamily:'PingFangSC-Medium',
    fontSize:ptd(56),
    color:'#FFFFFF',
    letterSpacing:2,
    marginRight:ptd(35),
  },
  loginBtn:{
    borderWidth:1,
    borderColor:'#FFFFFF',
    borderRadius:ptd(100),
    width:ptd(150),
    height:ptd(54),
  },
  loginTxt:{
    color:'#FFFFFF',
    letterSpacing:ptd(5),
    height:ptd(54),
    lineHeight:ptd(54),
    textAlign:'center',
    fontSize:ptd(30),
  },
  avatar:{
    width:ptd(80),
    height:ptd(80),
    borderRadius:ptd(40),
  },
  infoMoney:{
    fontSize:ptd(72),
    color:'#FFFFFF',
    letterSpacing:ptd(12),   
  },
  noLogin:{
    fontSize:ptd(24),
    color:'#FFFFFF',
    letterSpacing:ptd(4),
  },
  violateBlock:{
    backgroundColor:'#FFFFFF',
    borderRadius:ptd(20),
    width:ptd(670),
    paddingVertical:ptd(30) ,
    paddingRight:ptd(50),
    paddingLeft:ptd(40),
    position:'relative',
    top:ptd(-100),
    left:ptd(40),
    textAlign:'center',
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
    shadowColor:'#D5D5D5',
    shadowOffset:{width:0,height:ptd(10)},
    shadowOpacity:.5,
    shadowRadius:ptd(15),
    android: {
      borderColor: '#d8d8d8',
      borderWidth: 1
    },
  },
  navItem:{
    width:ptd(100),
  },
  navImage:{
    width:ptd(100),
    height:ptd(100),
    marginBottom:ptd(24),
  },
  navText:{
    width:ptd(100),
    fontSize:ptd(24),
    color:'#000000',
    textAlign:'center',
  },
  homeItem:{
    paddingHorizontal:ptd(40),
  },
  homeTitle:{
    width:ptd(670),
    marginTop:ptd(60),
    marginBottom:ptd(40),
    alignItems:'center',
    display:'flex',
    flexDirection:'row',
  },
  homeTitleShop:{
    justifyContent:'space-between',
  },
  homeTitleTxt:{
    fontFamily:'PingFangSC-Medium',
    fontSize:ptd(36),
    color:'#000000',
  },
  shopLabel:{
    fontFamily:'PingFangHK-Regular',
    fontSize:ptd(24),
    color:'#9B9B9B',
  },
  shopList:{
    width:ptd(670),
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
  },
  shopItem:{
    backgroundColor:'#FFFFFF',
    borderRadius:ptd(20),
    width:ptd(320),
    shadowColor:'#C4BEBE',
    shadowOffset:{width:0,height:ptd(8)},
    shadowRadius:ptd(10),
    shadowOpacity:.5,
    android: {
      borderColor: '#d8d8d8',
      borderWidth: 1
    },
  },
  shopImage:{
    width:ptd(320),
    height:ptd(410),
    borderRadius:ptd(20),
  },
  taskLabel:{
    width:ptd(100),
    height:ptd(36),
    lineHeight:ptd(36),
    fontFamily:'PingFangSC-Medium',
    fontSize:ptd(20),
    color:'#FFFFFF',
    textAlign:'center',
  },
  labelBg:{
    width:ptd(100),
    borderRadius:ptd(100),
    backgroundColor:'#1BC787',
    marginLeft:ptd(10),
  },
  taskContainer:{
    width:ptd(750),
    height:ptd(340),
    display:'flex',
    flexDirection:'row',
    paddingTop:ptd(20),
  },
  taskItem:{
    width:ptd(240),
    height:ptd(300),
    backgroundColor:'#FFFFFF',
    borderRadius:ptd(20),
    paddingTop:ptd(41),
    textAlign:'center',
    fontFamily:'PingFangSC-Medium',
    alignItems:'center',
    marginRight:ptd(40),
    shadowColor:'#C4BEBE',
    shadowOffset:{width:0,height:ptd(8)},
    shadowRadius:ptd(10),
    shadowOpacity:.5,
    android: {
      borderColor: '#d8d8d8',
      borderWidth: 1
    },
  },
  divider:{
    width:ptd(30),
    height:ptd(6),
    backgroundColor:'#D8D8D8',
    marginTop:ptd(12),
    marginBottom:ptd(20),
  },
  taskImage:{
    width:ptd(108),
    height:ptd(108),
  },
  taskTitle:{
    fontSize:ptd(30),
    color:'#333333',
    marginBottom:ptd(12),
    textAlign:'center',
  },
  rewardTitle:{
    fontSize:ptd(24),
    color:'#9B9B9B',
    textAlign:'center',
  }
})