import size, {ptd} from './SizeHelper.js'

module.exports = {
    productContainer: {
        height: size.height,
        paddingBottom: 198,
    },
    prodList: {
        width: 750,
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        paddingTop: 40,
        paddingHorizontal: 35,
    },
    prodItem: {
        position: 'relative',
        width: 330,
        height: 558,
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 10,
        marginBottom: 30,
        marginRight: 30,
        shadowOffset: {x:0, y:6},
        shadowRadius: 10,
        shadowColor: '#000',
        shadowOpacity: .16,
        android: {
          borderColor: '#d8d8d8',
          borderWidth: 1
        },
      },
      itemImage: {
        width: 310,
        height: 310,
      },
      itemTitle: {
        fontFamily: 'PingFangSC-Medium',
        fontSize: 32,
        color: '#333333',
        marginVertical: 10,
      },
      itemCount: {
        fontSize: 20,
        color: '#b5b5b5',
        marginBottom: 10,
      },
      itemPrice: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 25,
      },
      priceIcon: {
        width: 26,
        height: 26,
      },
      itemZuan: {
        fontFamily: 'PingFangSC-Medium',
        fontSize: 24,
        color: '#1BC787',
      },
      dhWrapper: {
        flex: 1,
        alignItems: 'center',
      },
      dhBtn: {
        backgroundColor: '#6FD786',
        shadowColor: '#9A9A9A',
        shadowOffset: {x:0, y:2},
        shadowRadius: 4,
        shadowOpacity: .5,
        borderRadius: 10,
        fontSize: 28,
        color: '#ffffff',
        width: 220,
        height: 52,
        lineHeight: 52,
        textAlign: 'center',
        fontFamily: 'PingFangSC-Medium',
      },
      prodMain: {
        paddingBottom: ptd(280),
        backgroundColor: '#f8f8f8',
        flex: 1,
      },
      prodInfo: {
        paddingVertical: ptd(20),
        paddingRight: ptd(40),
        paddingLeft: ptd(60),
        backgroundColor: '#fff',
      },
      prodName: {
        fontSize: ptd(38),
        color: '#333333',
        marginBottom: ptd(8),
      },
      prodCount: {
        flexDirection: 'row',
        justifyContent: 'space-between',
      },
      priceWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
      },
      prodZuan: {
        paddingLeft: ptd(15),
        fontSize: ptd(24),
        color: '#1BC787',
      },
      recordList: {
        marginVertical: ptd(30),
        paddingVertical: ptd(32),
        paddingRight: ptd(40),
        paddingLeft: ptd(60),
        backgroundColor: '#fff',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      recordTitle: {
        fontSize: ptd(24),
        color: '#333333',
      },
      recordeMore: {
        fontSize: ptd(24),
        color: '#9B9B9B',
      },
      recordItem: {
        paddingVertical: ptd(10),
        borderBottomColor: '#d7d9db',
        borderBottomWidth: ptd(2),
        justifyContent: 'space-between',
        fontSize: ptd(24),
        color: '#333333',
        alignItems: 'center',
      },
      itemName: {
        fontSize: ptd(30),
        lineHeight: ptd(80),
        justifyContent: "center",
        alignItems: 'center',
      },
      itemName: {
        width: ptd(80),
        height: ptd(80),
        borderRadius: ptd(40),
        marginRight: ptd(26),
      },
      recordItemTime: {
        fontFamily: 'PingFangSC-Regular',
        fontSize: ptd(22),
        color: '#9b9b9b',
      },
      content: {
        backgroundColor: '#fff',
        width: ptd(750),
        height: ptd(750),
        paddingTop: ptd(20),
        paddingHorizontal: ptd(30),
      },
      contentTitle: {
        fontSize: ptd(32),
        color: '#000000',
        textAlign: 'center',
      },
      contentWeb: {
        width: ptd(750),
        height: ptd(750),
      },
      bottom: {
        width: ptd(750),
        height: ptd(280),
        backgroundColor: '#fff',
        paddingTop: ptd(40),
      },
      detailDhBtn: {
        backgroundColor: '#1BC787',
        shadowColor: '#805877',
        shadowOffset: {x:0, y:10},
        shadowOpacity: 0.24,
        shadowRadius: ptd(10),
        borderRadius: ptd(100),
        width: ptd(600),
        height: ptd(98),
        lineHeight: ptd(98),
        marginVertical: ptd(20),
        marginHorizontal: ptd(75),
      },
      dhBtnTxt: {
        fontSize: ptd(30),
        color: '#ffffff',
        textAlign: 'center',
        height: ptd(98),
        lineHeight: ptd(98),
      },
      dhFoot: {
        width: ptd(690),
        position: 'relative',
        height: ptd(98),
        backgroundColor: '#333333',
        paddingLeft: ptd(40),
        alignItems: 'center',
        flexDirection: 'row',
        marginTop: ptd(27),
        marginHorizontal: ptd(30),
      },
      dhFootTxt: {
        color: '#fff',
        textAlign: 'left',
      },
      dhFoot2: {
        width: ptd(296),
        height: ptd(110),
        position: 'absolute',
        top: ptd(-10),
        right: 0,
      },
      dhFootBg: {
        width: ptd(296),
        height: ptd(110),
      },
      dhFoot2Txt: {
        height: ptd(110),
        lineHeight: ptd(110),
        fontSize: ptd(38),
        color: '#ffffff',
        textAlign: 'center',
      },
      xieyi: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingBottom: ptd(40),
        marginTop: ptd(22),
      },
      xieyiTxt: {
        fontFamily: 'PingFangHK-Regular',
        fontSize: ptd(22),
        color: '#9b9b9b',
      },
      bottomDh: {
        width: ptd(690),
      },
      cbg: {
        width: ptd(18),
        height: ptd(18),
        marginRight: ptd(8),
      },
      wrapper: {
        width: ptd(750),
        height: ptd(750),
      },
      slider: {
        width: ptd(750),
        height: ptd(750),
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
      },
      prodImage: {
        width: ptd(750),
        height: ptd(750)
      },
      subtitle: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      priceIcon: {
        width: ptd(26),
        height: ptd(26),
      },
      blue: {
        color: '#1BC787',
        fontSize: ptd(24),
      },
      subtxt: {
        color: '#9b9b9b',
        fontSize: ptd(24),
      },
      tips: {
        fontSize: ptd(24),
        color: '#9b9b9b',
        textAlign: 'center',
      },
}